git:
  platform_automation_pipelines:
    uri: git@github.com:dbha/my-opsman-install.git
    branch: master
  platform_automation_configs:
    uri: git@github.com:dbha/my-opsman-install.git
    branch: master
  user:
    email: user@vmware.com
    username: "Platform Automation Bot"
  private_key: ((git_private_key.private_key))

pivnet:
  token: ((pivnet_token))

s3:
  endpoint: https://s3.ap-northeast-2.amazonaws.com
  access_key_id: ((s3_access_key_id))
  secret_access_key: ((s3_secret_access_key))
  region_name: "ap-northeast-2"
  buckets:
    platform_automation: dbha-automation-test
    #pivnet_products: awstest-pivnet-products
    pivnet_products: dbha-automation-test
    installation: dbha-automation-test
    bbr-backup: dbha-bbr-backup

#credhub:
#  server: https://credhub.pksdemo.net:8844
#  ca_cert: ""
#  client: ((credhub_client.username))
#  secret: ((credhub_client.password))
#  interpolate_folders: ((foundation))/config ((foundation))/env ((foundation))/download-products

