git:
  platform_automation_pipelines:
    uri: git@github.com:dbha/my-opsman-install.git
    branch: master
  platform_automation_configs:
    uri: git@github.com:dbha/my-opsman-install.git
    branch: master
  user:
    email: user@pivotal.io
    username: "Platform Automation Bot"
  private_key: ((git_private_key.private_key))